include("benchmarking.jl")
include("soa_cpu.jl")
include("cpu_threaded.jl")
case = ARGS[1]
input = ProcessCase(Float64, case)
soaInput = toSOAInput(input)
prep = prepf(input)
pde = Div{Float64, UpwindScheme{Float64}}(UpwindScheme{Float64}(), 1.0) + Laplace(1.0)
batches = getBatches(input)
suite = BenchmarkGroup()
suite["cpu"] = BenchmarkGroup(["cpu"])
suite["cpu"][case] = BenchmarkGroup(["cpu", case])
# suite["cpu"][case]["faceBased"] = BenchmarkGroup(["cpu", "faceBased", case])
# suite["cpu"][case]["cellBased"] = BenchmarkGroup(["cpu", "cellBased", case])
# suite["cpu"][case]["globalFaceBased"] = BenchmarkGroup(["cpu", "globalFaceBased", case])
# suite["cpu"][case]["batchedFace"] = BenchmarkGroup(["cpu", "batchedFace", case])
nthreads = Threads.nthreads()
if nthreads > 1
    suite["cpu"][case]["faceBased"]["SOAFusedFaceBasedAssemblyThreaded-$nthreads"] = @benchmarkable SOAFusedFaceBasedAssemblyThreaded($soaInput, $prep..., $pde)
    suite["cpu"][case]["globalFaceBased"]["FusedGlobalFaceBased-$nthreads"] = @benchmarkable SOAFusedGlobalFaceBasedAssemblyThreaded($soaInput, $prep...,$pde)
    suite["cpu"][case]["batchedFace"]["FusedBatchedFaceBased-$nthreads"] = @benchmarkable SOAFusedBatchedFaceBasedAssemblyThreaded($soaInput, $prep..., $batches, $pde)
    suite["cpu"][case]["cellBased"]["FusedCellBased-$nthreads"] = @benchmarkable SOAFusedCellBasedAssemblyThreaded($soaInput, $prep...,$pde)
else
    suite["cpu"][case]["faceBased"]["SOAFusedFaceBasedAssembly-serial"] = @benchmarkable SOAFusedFaceBasedAssembly($soaInput, $prep..., $pde)
    suite["cpu"][case]["globalFaceBased"]["FusedGlobalFaceBased-serial"] = @benchmarkable SOAFusedGlobalFaceBasedAssembly($soaInput, $prep...,$pde)
    suite["cpu"][case]["batchedFace"]["FusedBatchedFaceBased-serial"] = @benchmarkable SOAFusedBatchedFaceBasedAssembly($soaInput, $prep..., $batches, $pde)
    suite["cpu"][case]["cellBased"]["FusedCellBased-serial"] = @benchmarkable SOAFusedCellBasedAssembly($soaInput, $prep...,$pde)

end
results = run(suite, verbose=true)
processResults(results, "scaling.csv", Float64)